"""
Pure functions used by install_systemd.sh.

设计原则: 全部是纯函数, 不碰文件系统, 不调外部命令, 不依赖网络。
shell 脚本只负责: 1) 读环境, 2) 调这些函数得到字符串, 3) 写文件 / 跑命令。
"""
import re
from typing import List


_PG_BIN_RE = re.compile(r"/usr/lib/postgresql/(\d+)/bin/")


def detect_pg_version(pg_bin_path: str) -> str:
    """从 /usr/lib/postgresql/<ver>/bin/postgres 路径里抠出版本号。"""
    m = _PG_BIN_RE.search(pg_bin_path)
    if not m:
        raise ValueError(
            f"Cannot detect PG version from path: {pg_bin_path!r}. "
            "Expected /usr/lib/postgresql/<ver>/bin/..."
        )
    return m.group(1)


def pg_hba_local_md5_line() -> str:
    """生成 127.0.0.1/32 md5 鉴权行 (追加到 pg_hba.conf 末尾)。"""
    return "host all all 127.0.0.1/32 md5"


def postgres_conf_overrides(port: int) -> str:
    """生成 postgresql.conf 的覆盖段 (append-only, 不会覆盖已有设置)。

    监听 loopback only, 显式端口, unix socket 在 /var/run/postgresql。
    """
    return "\n".join([
        "# --- WDG systemd override ---",
        "listen_addresses = '127.0.0.1'",
        f"port = {port}",
        "unix_socket_directories = '/var/run/postgresql'",
        "# --- end WDG ---",
        "",
    ])


def initdb_command(
    *,
    pg_bin: str,
    data_dir: str,
    encoding: str = "UTF8",
    locale: str = "C",
) -> List[str]:
    """构造 initdb 命令 (argv 形式, 方便测试)。

    必须用 sudo -u postgres 跑 (PG 拒绝非 postgres 用户 initdb)。
    """
    return [
        "sudo", "-u", "postgres",
        f"{pg_bin}/initdb",
        "-D", data_dir,
        f"--encoding={encoding}",
        f"--locale={locale}",
    ]


def env_file_contents(*, role: str, pg_data: str, pg_port: int) -> str:
    """生成 /etc/wdg/postgres.env (主) 或 postgres-agent.env。

    不放密码 — 密码通过 SQL ALTER USER 单独设置, 不进 env。
    """
    return "\n".join([
        f"# WDG PostgreSQL ({role}) — generated by install_systemd.sh",
        f"PGDATA={pg_data}",
        f"PGPORT={pg_port}",
        "PG_OOM_ADJ_FILE=/proc/self/oom_score_adj",
        "PG_OOM_ADJ_VALUE=0",
        "",
    ])
